services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped
    volumes:
      - .:/app

  nginx:
      image: nginx:latest
      container_name: nginx_proxy
      depends_on:
        - app
      volumes:
        - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      environment:
        - DOMAIN=expo4.madt.pro
      ports:
        - "80:80"
        - "443:443"
      restart: unless-stopped
      command: ["/bin/bash", "-c", "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c"
    command: >
      "sleep 15 &&
      certbot certonly --webroot --webroot-path=/var/www/certbot
      --email madt@madt.pro --agree-tos --no-eff-email
      -d expo4.madt.pro"
